### ISSUE TITLE
Salt and key not received for user (status code 401)

### ISSUE THREAD

**Issue by evanes68** [escalate/python-loxone-ws-client#1]
when I run again issue is gone. Sorry for this message...

**Comment by escalate** [comment]
Hello @evanes68.
I have the same issue you described. I think it is a bug but I can't find the root cause of it.
Because this library is still under development it would be very nice if you could help me to find the problem root cause.
Best regards 
Felix

**Comment by evanes68** [comment]
Felix,
I solved the issue by using openHAB with loxone plug-in. I do find this overkill and very complex to setup.

But if i can help i can try. How do you think I can help?

Evert
